project_id = "paywwbuqycovjopryele"

[functions.check-scheduled-bookings]
verify_jwt = false

[functions.admin-upload-qr]
verify_jwt = false

[functions.send-fcm]
verify_jwt = false

[functions.booking-notifications]
verify_jwt = false

[functions.notify-next-tier]
verify_jwt = false

[functions.complete-booking-with-otp]
verify_jwt = false

[functions.send-webpush]
verify_jwt = false
