export const DEMO_WORKER = {
  id: 'demo-worker-id',
  user_id: null,
  full_name: 'Demo Partner',
  phone: '9999999999',
  service_types: ['maid', 'cook', 'bathroom_cleaning'],
  communities: ['downtown'],
  community: 'downtown',
  selected_community_id: null,
  cook_cuisine_tags: ['north_indian', 'south_indian'],
  is_active: true,
  is_available: true,
  is_busy: false,
  rating: 4.8,
  total_ratings: 127,
  total_earnings: 45000,
  upi_id: 'demo@paytm',
  upi_qr_url: null,
  upi_qr_payload: null,
  upi_qr_uploaded_at: null,
  photo_url: null,
  fcm_token: null,
  last_active_at: new Date().toISOString(),
  last_seen_at: new Date().toISOString(),
  last_lat: null,
  last_lng: null,
  location_enabled: false,
  in_geofence: false,
  respect_availability: true,
  timezone: 'Asia/Kolkata',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const DEMO_ACTIVE_JOB = {
  id: 'demo-booking-active',
  user_id: 'demo-user-id',
  worker_id: 'demo-worker-id',
  service_type: 'maid',
  booking_type: 'instant',
  community: 'downtown',
  flat_no: 'A-101',
  flat_size: '2bhk',
  cust_name: 'Rajesh Kumar',
  cust_phone: '9876543210',
  status: 'accepted',
  price_inr: 350,
  payout_amount: 280,
  notes: 'Please bring cleaning supplies',
  scheduled_date: null,
  scheduled_time: null,
  maid_tasks: ['sweeping_mopping', 'dishes', 'bathroom_cleaning'] as any,
  bathroom_count: null,
  family_count: null,
  food_pref: null,
  cook_cuisine_pref: null,
  cook_gender_pref: null,
  worker_name: 'Demo Partner',
  worker_phone: '9999999999',
  worker_photo_url: null,
  worker_upi: 'demo@paytm',
  is_demo: true,
  prealert_sent: false,
  created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(), // 30 mins ago
  updated_at: new Date().toISOString(),
  accepted_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  assigned_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  confirmed_at: null,
  on_the_way_at: null,
  started_at: null,
  completed_at: null,
  cancelled_at: null,
  cancel_reason: null,
  cancel_source: null,
  can_cancel_until: null,
  auto_complete_after_minutes: 180,
  auto_complete_at: null,
  pay_enabled_at: null,
  user_marked_paid_at: null,
};

export const DEMO_BOOKINGS = [
  {
    id: 'demo-booking-1',
    user_id: 'demo-user-id',
    worker_id: 'demo-worker-id',
    service_type: 'cook',
    booking_type: 'scheduled',
    community: 'downtown',
    flat_no: 'B-205',
    flat_size: '3bhk',
    cust_name: 'Priya Sharma',
    cust_phone: '9988776655',
    status: 'completed',
    price_inr: 500,
    payout_amount: 400,
    notes: 'North Indian food preferred',
    scheduled_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    scheduled_time: '10:00',
    maid_tasks: null,
    bathroom_count: null,
    family_count: 4,
    food_pref: 'veg',
    cook_cuisine_pref: 'north_indian',
    cook_gender_pref: null,
    worker_name: 'Demo Partner',
    worker_phone: '9999999999',
    worker_photo_url: null,
    worker_upi: 'demo@paytm',
    is_demo: true,
    prealert_sent: true,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    accepted_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    assigned_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    confirmed_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    on_the_way_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    cancelled_at: null,
    cancel_reason: null,
    cancel_source: null,
    can_cancel_until: null,
    auto_complete_after_minutes: 180,
    auto_complete_at: null,
    pay_enabled_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    user_marked_paid_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'demo-booking-2',
    user_id: 'demo-user-id',
    worker_id: 'demo-worker-id',
    service_type: 'bathroom_cleaning',
    booking_type: 'instant',
    community: 'downtown',
    flat_no: 'C-302',
    flat_size: '2bhk',
    cust_name: 'Amit Patel',
    cust_phone: '9123456789',
    status: 'completed',
    price_inr: 200,
    payout_amount: 160,
    notes: 'Deep cleaning needed',
    scheduled_date: null,
    scheduled_time: null,
    maid_tasks: null,
    bathroom_count: 2,
    family_count: null,
    food_pref: null,
    cook_cuisine_pref: null,
    cook_gender_pref: null,
    worker_name: 'Demo Partner',
    worker_phone: '9999999999',
    worker_photo_url: null,
    worker_upi: 'demo@paytm',
    is_demo: true,
    prealert_sent: false,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    accepted_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    assigned_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    confirmed_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    on_the_way_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    cancelled_at: null,
    cancel_reason: null,
    cancel_source: null,
    can_cancel_until: null,
    auto_complete_after_minutes: 180,
    auto_complete_at: null,
    pay_enabled_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    user_marked_paid_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
