import { Database } from "@/integrations/supabase/types";

type Worker = Database["public"]["Tables"]["workers"]["Row"];
type Booking = Database["public"]["Tables"]["bookings"]["Row"];

export const DEMO_WORKER: Worker = {
  id: 'demo-worker-id',
  user_id: 'demo-user-id',
  full_name: 'Priya Sharma',
  phone: '+919876543210',
  service_types: ['maid', 'bathroom_cleaning'],
  communities: ['Prestige High Fields', 'Brigade Meadows'],
  community: null,
  is_active: true,
  is_available: true,
  is_busy: false,
  upi_id: 'priya.sharma@paytm',
  rating: 4.8,
  total_ratings: 127,
  total_earnings: 45800,
  created_at: '2024-01-15T10:30:00Z',
  updated_at: new Date().toISOString(),
  photo_url: null,
  fcm_token: null,
  last_active_at: new Date().toISOString(),
  last_seen_at: new Date().toISOString(),
  last_lat: null,
  last_lng: null,
  in_geofence: null,
  location_enabled: null,
  respect_availability: true,
  selected_community_id: null,
  timezone: null,
};

export const DEMO_ACTIVE_JOB: Booking = {
  id: 'demo-booking-active',
  user_id: 'demo-customer-1',
  cust_name: 'Rajesh Kumar',
  cust_phone: '+919123456789',
  community: 'Prestige High Fields',
  flat_no: 'A-402',
  service_type: 'maid',
  booking_type: 'instant',
  scheduled_date: new Date().toISOString().split('T')[0],
  scheduled_time: '10:00',
  status: 'accepted',
  worker_id: 'demo-worker-id',
  worker_name: 'Priya Sharma',
  worker_phone: '+919876543210',
  worker_upi: 'priya.sharma@paytm',
  worker_photo_url: null,
  price_inr: 400,
  payout_amount: 360,
  created_at: new Date(Date.now() - 3600000).toISOString(),
  updated_at: new Date().toISOString(),
  accepted_at: new Date(Date.now() - 1800000).toISOString(),
  assigned_at: new Date(Date.now() - 3600000).toISOString(),
  started_at: null,
  completed_at: null,
  cancelled_at: null,
  on_the_way_at: null,
  confirmed_at: null,
  cancel_reason: null,
  cancel_source: null,
  notes: 'Please bring your own cleaning supplies. Main bedroom and living room need thorough cleaning.',
  bathroom_count: null,
  family_count: null,
  flat_size: null,
  maid_tasks: null,
  cook_cuisine_pref: null,
  cook_gender_pref: null,
  food_pref: null,
  auto_complete_after_minutes: 60,
  auto_complete_at: null,
  can_cancel_until: null,
  pay_enabled_at: null,
  user_marked_paid_at: null,
  prealert_sent: false,
  is_demo: true,
};

export const DEMO_BOOKINGS: Booking[] = [
  DEMO_ACTIVE_JOB,
  {
    id: 'demo-booking-1',
    user_id: 'demo-customer-2',
    cust_name: 'Meera Reddy',
    cust_phone: '+919234567890',
    community: 'Brigade Meadows',
    flat_no: 'B-105',
    service_type: 'bathroom_cleaning',
    booking_type: 'scheduled',
    scheduled_date: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    scheduled_time: '14:00',
    status: 'assigned',
    worker_id: 'demo-worker-id',
    worker_name: 'Priya Sharma',
    worker_phone: '+919876543210',
    worker_upi: 'priya.sharma@paytm',
    worker_photo_url: null,
    price_inr: 250,
    payout_amount: 225,
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: new Date().toISOString(),
    accepted_at: null,
    assigned_at: new Date(Date.now() - 7200000).toISOString(),
    started_at: null,
    completed_at: null,
    cancelled_at: null,
    on_the_way_at: null,
    confirmed_at: null,
    cancel_reason: null,
    cancel_source: null,
    notes: 'Deep cleaning required for 2 bathrooms',
    bathroom_count: 2,
    family_count: null,
    flat_size: null,
    maid_tasks: null,
    cook_cuisine_pref: null,
    cook_gender_pref: null,
    food_pref: null,
    auto_complete_after_minutes: 60,
    auto_complete_at: null,
    can_cancel_until: null,
    pay_enabled_at: null,
    user_marked_paid_at: null,
    prealert_sent: false,
    is_demo: true,
  },
  {
    id: 'demo-booking-2',
    user_id: 'demo-customer-3',
    cust_name: 'Anil Patel',
    cust_phone: '+919345678901',
    community: 'Prestige High Fields',
    flat_no: 'C-201',
    service_type: 'maid',
    booking_type: 'instant',
    scheduled_date: new Date(Date.now() - 86400000).toISOString().split('T')[0],
    scheduled_time: '09:00',
    status: 'completed',
    worker_id: 'demo-worker-id',
    worker_name: 'Priya Sharma',
    worker_phone: '+919876543210',
    worker_upi: 'priya.sharma@paytm',
    worker_photo_url: null,
    price_inr: 600,
    payout_amount: 540,
    created_at: new Date(Date.now() - 172800000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
    accepted_at: new Date(Date.now() - 172800000).toISOString(),
    assigned_at: new Date(Date.now() - 172800000).toISOString(),
    started_at: new Date(Date.now() - 172800000 + 3600000).toISOString(),
    completed_at: new Date(Date.now() - 172800000 + 14400000).toISOString(),
    cancelled_at: null,
    on_the_way_at: null,
    confirmed_at: new Date(Date.now() - 172800000).toISOString(),
    cancel_reason: null,
    cancel_source: null,
    notes: 'Complete house cleaning including kitchen',
    bathroom_count: null,
    family_count: null,
    flat_size: '3bhk',
    maid_tasks: ['floor_cleaning', 'dish_washing'],
    cook_cuisine_pref: null,
    cook_gender_pref: null,
    food_pref: null,
    auto_complete_after_minutes: 60,
    auto_complete_at: null,
    can_cancel_until: null,
    pay_enabled_at: new Date(Date.now() - 172800000 + 14400000).toISOString(),
    user_marked_paid_at: new Date(Date.now() - 172800000 + 15000000).toISOString(),
    prealert_sent: false,
    is_demo: true,
  },
  {
    id: 'demo-booking-3',
    user_id: 'demo-customer-4',
    cust_name: 'Lakshmi Iyer',
    cust_phone: '+919456789012',
    community: 'Brigade Meadows',
    flat_no: 'D-302',
    service_type: 'maid',
    booking_type: 'scheduled',
    scheduled_date: new Date(Date.now() - 259200000).toISOString().split('T')[0],
    scheduled_time: '15:00',
    status: 'completed',
    worker_id: 'demo-worker-id',
    worker_name: 'Priya Sharma',
    worker_phone: '+919876543210',
    worker_upi: 'priya.sharma@paytm',
    worker_photo_url: null,
    price_inr: 400,
    payout_amount: 360,
    created_at: new Date(Date.now() - 345600000).toISOString(),
    updated_at: new Date(Date.now() - 259200000).toISOString(),
    accepted_at: new Date(Date.now() - 345600000).toISOString(),
    assigned_at: new Date(Date.now() - 345600000).toISOString(),
    started_at: new Date(Date.now() - 345600000 + 3600000).toISOString(),
    completed_at: new Date(Date.now() - 345600000 + 10800000).toISOString(),
    cancelled_at: null,
    on_the_way_at: null,
    confirmed_at: new Date(Date.now() - 345600000).toISOString(),
    cancel_reason: null,
    cancel_source: null,
    notes: 'Weekly cleaning',
    bathroom_count: null,
    family_count: null,
    flat_size: '2bhk',
    maid_tasks: ['floor_cleaning'],
    cook_cuisine_pref: null,
    cook_gender_pref: null,
    food_pref: null,
    auto_complete_after_minutes: 60,
    auto_complete_at: null,
    can_cancel_until: null,
    pay_enabled_at: new Date(Date.now() - 345600000 + 10800000).toISOString(),
    user_marked_paid_at: new Date(Date.now() - 345600000 + 11000000).toISOString(),
    prealert_sent: false,
    is_demo: true,
  },
];

export function isGuestMode(): boolean {
  return localStorage.getItem('guest_mode') === 'true';
}
